Algoritmo "Sucessor"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : 5) (COMPLEMENTO) - Lê o número do teclado e diz seu sucessor
// Autor(a)    : Gustavo Souza Santana
// Data atual  : 31/08/2026
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um numero: ")
Leia(numero)
numero<- numero + 1
Escreva("O sucessor do seu numero é:", numero)
Fimalgoritmo