Algoritmo "L05A"
// Disciplina: [Lógica de Programação com JavaScript]
// Professor: Jailson Costa dos Santos
// Descrição: Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a): Gustavo Souza Santana
// Data atual: 28/09/2026

Var
   numero: inteiro
   quadrado: inteiro

Inicio
   Escreval("  QUADRADOS DOS NÚMEROS (15 A 200) ")
   Escreval("")

   para numero de 15 ate 200 faca
      quadrado <- numero * numero
      Escreval(numero, " ao quadrado = ", quadrado)
   fimpara

   Escreval("")
   Escreval("--------------------------------------------")
   Escreval("Cálculo dos quadrados concluído com sucesso!")
   Escreval("--------------------------------------------")
   Escreval("")

Fimalgoritmo