Algoritmo "L05B"
// Disciplina: [Lógica de Programação com JavaScript]
// Professor: Jailson Costa dos Santos
// Descrição: Apresentar os resultados de uma tabuada de multiplicar
// (de 1 até 10) de um número qualquer.
// Autor(a): Gustavo Souza Santana
// Data atual: 28/09/2026

Var
   numero, contadora, resultado: inteiro

Inicio
   Escreva("Digite um número para ver a tabuada: ")
   Leia(numero)

   Para contadora de 1 até 10 faca
      resultado <- numero * contadora
      Escreval(numero, " x ", contadora, " = ", resultado)
   fimPara

Fimalgoritmo