Algoritmo "L05E"
// Disciplina: [Lógica de Programação com JavaScript]
// Professor: Jailson Costa dos Santos
// Descrição: Apresentar todos os valores numéricos inteiros
// ímpares situados na faixa de 0 a 20.
// Autor(a): Gustavo Souza Santana
// Data atual: 28/09/2026

Var
   number: inteiro

Inicio
   Escreval("  NUMEROS IMPARES DE 0 A 20  ")
   Escreval("")
   Escreval("Numeros impares:")

   para number de 0 ate 20 faca
      se number Mod 2 <> 0 entao
         Escreval(number)
      fimse
   fimPara

Fimalgoritmo