Algoritmo "L05F"
// Disciplina: [Lógica de Programação com JavaScript]
// Professor: Jailson Costa dos Santos
// Descrição: Apresentar todos os números divisíveis por 4
// que sejam menores que 200.
// Autor(a): Gustavo Souza Santana
// Data atual: 28/09/2026

Var
   contador: inteiro

Inicio
   Escreval("***************************************")
   Escreval("     NÚMEROS DIVISÍVEIS POR 4 < 200    ")
   Escreval("***************************************")
   Escreval("")

   para contador de 1 ate 199 faca
      se contador % 4 = 0 entao
         Escreval("Número divisível por 4: ", contador)
      fimse
   fimpara

   Escreval("")
   Escreval("-----------------------------------------")
   Escreval("     Listagem finalizada com sucesso!    ")
   Escreval("-----------------------------------------")
   Escreval("")

Fimalgoritmo