Algoritmo "AreaRetangulo"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : 6) Escreva um algoritmo para ler as dimensões de um retângulo
//(base e altura), calcular e escrever a
// área do retângulo.
// Gustavo Souza Santana
// Data atual  : 31/08/2026
Var
// Seção de Declarações das variáveis 
   base, altura, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite a base do retângulo: ")
   Leia(base)
   Escreva("Digite a altura do retângulo: ")
   Leia(altura)
   area<- base * altura
   Escreva("O Resultado da area do retângulo é: ", area)

Fimalgoritmo