Algoritmo "ValorDoNumero"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : 15) Ler um valor e escrever se é positivo ou negativo
// (considere o valor zero como positivo).
// Autor(a)    : Gustavo Souza Santana
// Data atual  : 31/08/2026
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um número :")
   Leia(numero)
   se numero>= 0 entao
      Escreval("Número positivo")
   senao
      Escreval("Número negativo")
   fimse

Fimalgoritmo